image: node:12
pipelines:
  branches:
    master:
      - step:
          script:
            - yarn
      - step:
          name: Publish
          deployment: production
          script:
            - pipe: atlassian/serverless-deploy:0.1.3
              variables:
                DB_HOST: $DB_HOST
                DB_DATABASE: $DB_DATABASE
                DB_USERNAME: $DB_USERNAME
                DB_PROPERTIES_DATABASE: $DB_PROPERTIES_DATABASE
                MAILGUN_API_KEY: $MAILGUN_API_KEY
                MAILGUN_DOMAIN: $MAILGUN_DOMAIN
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
