service: brokalys-pinger

provider:
  name: aws
  region: eu-west-1
  runtime: nodejs12.x
  timeout: 3
  cfLogs: true
  versionFunctions: false
  environment:
      DB_HOST: ${env:DB_HOST}
      DB_DATABASE: ${env:DB_DATABASE}
      DB_USERNAME: ${env:DB_USERNAME}
      DB_PROPERTIES_DATABASE: ${env:DB_PROPERTIES_DATABASE}
      MAILGUN_API_KEY: ${env:MAILGUN_API_KEY}
      MAILGUN_DOMAIN: ${env:MAILGUN_DOMAIN}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - SNS:Publish
      Resource: "arn:aws:sns:eu-west-1:*:*"

functions:
  init:
    handler: src/init.run
    events:
      - schedule: rate(5 minutes)
  pinger:
    handler: src/pinger.run
    events:
      - sns: pinger

custom:
  alerts:
    topics:
      alarm:
        topic: ${self:service}-${opt:stage}-critical-alerts-alarm
        notifications:
          - protocol: email
            endpoint: matiss@brokalys.com
    alarms:
      - functionThrottles
      - functionErrors
      - functionInvocations
      - functionDuration

plugins:
  - serverless-plugin-aws-alerts
