CREATE TABLE `pinger_emails` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `id_hash` varchar(36) NOT NULL DEFAULT '',
  `email` varchar(255) DEFAULT NULL,
  `categories` text,
  `types` text,
  `price_min` int(11) DEFAULT NULL,
  `price_max` int(11) DEFAULT NULL,
  `price_type` enum('total','sqm') DEFAULT 'total',
  `rooms_min` int(11) DEFAULT NULL,
  `rooms_max` int(11) DEFAULT NULL,
  `area_m2_min` int(11) DEFAULT NULL,
  `area_m2_max` int(11) DEFAULT NULL,
  `floor_min` int(11) DEFAULT NULL,
  `floor_max` int(11) DEFAULT NULL,
  `location` text,
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `limit_reached_at` timestamp NULL DEFAULT NULL,
  `unsubscribed_at` timestamp NULL DEFAULT NULL,
  `description` varchar(255) DEFAULT NULL,
  `unsubscribe_key` varchar(45) DEFAULT NULL,
  `frequency` enum('immediate','daily','weekly','monthly') DEFAULT 'immediate',
  `marketing` tinyint(4) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_hash` (`id_hash`),
  KEY `last_check_at` (`email`),
  KEY `unsubscribed_at` (`unsubscribed_at`)
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;
